### ISSUE TITLE
NOT WORKING ON XP

### ISSUE THREAD

**Issue by ComandPromt** [hvdwolf/jExifToolGUI#106]
![Selección_006](https://user-images.githubusercontent.com/17002667/104628612-b5cc1280-5698-11eb-8704-15ca9ef52d20.png)

# LOG

#logback.classic pattern: %d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
14:19:48.085 [main] INFO  org.hvdw.jexiftoolgui.Application - Start application
14:19:48.095 [main] INFO  org.hvdw.jexiftoolgui.Application - Continuing in system language or, if not translated, in English
14:19:48.666 [AWT-EventQueue-0] INFO  org.hvdw.jexiftoolgui.mainScreen - string for DB: C:\Documents and Settings\Administrador\jexiftoolgui_data\jexiftoolgui.db
14:19:51.500 [AWT-EventQueue-0] INFO  org.hvdw.jexiftoolgui.Utils - preference exiftool returned: null
14:19:51.550 [AWT-EventQueue-0] ERROR o.h.j.controllers.CommandRunner - IOException error
java.io.IOException: Cannot run program "where": CreateProcess error=2, El sistema no puede hallar el archivo especificado
	at java.lang.ProcessBuilder.start(Unknown Source)
	at org.hvdw.jexiftoolgui.controllers.CommandRunner.runCommand(CommandRunner.java:27)
	at org.hvdw.jexiftoolgui.Utils.getExiftoolPath(Utils.java:1251)
	at org.hvdw.jexiftoolgui.controllers.CheckPreferences.checkPreferences(CheckPreferences.java:45)
	at org.hvdw.jexiftoolgui.mainScreen.<init>(mainScreen.java:3624)
	at org.hvdw.jexiftoolgui.mainScreen.createAndShowGUI(mainScreen.java:3725)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, El sistema no puede hallar el archivo especificado
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 20 common frames omitted
14:19:51.550 [AWT-EventQueue-0] INFO  org.hvdw.jexiftoolgui.Utils - exiftool_found mentions: true
14:19:51.770 [AWT-EventQueue-0] ERROR o.h.j.controllers.UpdateActions - Successfully did: creating the table userFavorites (1.4)
14:19:51.770 [AWT-EventQueue-0] ERROR o.h.j.controllers.UpdateActions - Successfully did: drop table CustomView
14:19:51.770 [AWT-EventQueue-0] ERROR o.h.j.controllers.UpdateActions - Successfully did: drop table CustomViewLines
14:19:51.770 [AWT-EventQueue-0] ERROR o.h.j.controllers.UpdateActions - Successfully did: drop table CustomEdit
14:19:51.770 [AWT-EventQueue-0] ERROR o.h.j.controllers.UpdateActions - Successfully did: drop table CustomEditLines
14:19:51.770 [AWT-EventQueue-0] ERROR o.h.j.controllers.UpdateActions - Successfully did: creating the table CustomMetadataset (1.6)
14:19:51.770 [AWT-EventQueue-0] ERROR o.h.j.controllers.UpdateActions - Successfully did: creating the table CustomMetadatasetLines (1.6)
14:19:51.850 [AWT-EventQueue-0] INFO  org.hvdw.jexiftoolgui.mainScreen - OS name MICROSOFT
14:19:51.860 [AWT-EventQueue-0] ERROR o.h.j.controllers.CommandRunner - IOException error
java.io.IOException: Cannot run program "IOException errorCannot run program "where": CreateProcess error=2, El sistema no puede hallar el archivo especificado": CreateProcess error=2, El sistema no puede hallar el archivo especificado
	at java.lang.ProcessBuilder.start(Unknown Source)
	at org.hvdw.jexiftoolgui.controllers.CommandRunner.runCommand(CommandRunner.java:27)
	at org.hvdw.jexiftoolgui.mainScreen.setProgramScreenTexts(mainScreen.java:3545)
	at org.hvdw.jexiftoolgui.mainScreen.<init>(mainScreen.java:3679)
	at org.hvdw.jexiftoolgui.mainScreen.createAndShowGUI(mainScreen.java:3725)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.IOException: CreateProcess error=2, El sistema no puede hallar el archivo especificado
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 19 common frames omitted

**Comment by mrtngrsbch** [comment]
#locate exiftool

**Comment by hvdwolf** [comment]
Please install exiftool as described on the release page and the website.
Also: Windows XP is not supported by Microsoft anymore for many, many years. Same for Windows 7 since 1½ year.

I assume JTG will work, but I don't give guarantees.

**Comment by ComandPromt** [comment]
I have tested with windows 7 and raspberry pi 4 and it works perfectly. For debian you have to run sudo apt install -y libimage-exiftool-perl
