### ISSUE TITLE
Exception in thread "pool-2-thread-1" java.lang.NullPointerException

### ISSUE THREAD

**Issue by coolboss77** [hvdwolf/jExifToolGUI#121]
I have a problem when I choose a pic;  I tried many pictures but a few of them doesn't work well  
Exception in thread "pool-2-thread-1" java.lang.NullPointerException
	at javax.swing.ImageIcon.<init>(ImageIcon.java:240)
	at org.hvdw.jexiftoolgui.controllers.ImageFunctions.createIcon(ImageFunctions.java:420)
	at org.hvdw.jexiftoolgui.controllers.ImageFunctions.analyzeImageAndCreateIcon(ImageFunctions.java:280)
	at org.hvdw.jexiftoolgui.Utils.displayFiles(Utils.java:853)
	at org.hvdw.jexiftoolgui.Utils$1.run(Utils.java:736)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by hvdwolf** [comment]
If you know which picture it is, please try with that picture alone. If it is consistent, please attach that picture.

**Comment by hvdwolf** [comment]
Probably be solved with new loading mechanism in 1.10.
Without further response from OP, this one is closed.
