### ISSUE TITLE
Linux AppImage Startup Error

### ISSUE THREAD

**Issue by sam302** [hvdwolf/jExifToolGUI#84]
I downloaded the appimage on Fedora 33 and made it executable.  When I run the appimage the first time the splash screen pops up and then goes away but nothing else happens.  When I tried to run it again I got the splash screen and then a popup message that says

_**"The Exiftool specified in your preferences does not exist.  Did you move/rename/delete it?"**_

I installed Exiftool from the website using the instructions there and did not move anything.  When I click "OK" on the popup it goes away and then these errors are in the terminal: 

`ERROR o.h.j.controllers.CommandRunner - IOException error
java.io.IOException: Cannot run program "IOException errorCannot run program "which": error=2, No such file or directory": error=2, No such file or directory
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at org.hvdw.jexiftoolgui.controllers.CommandRunner.runCommand(CommandRunner.java:28)
	at org.hvdw.jexiftoolgui.mainScreen.setProgramScreenTexts(mainScreen.java:3409)
	at org.hvdw.jexiftoolgui.mainScreen.<init>(mainScreen.java:3543)
	at org.hvdw.jexiftoolgui.mainScreen.createAndShowGUI(mainScreen.java:3568)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.io.IOException: error=2, No such file or directory
	at java.base/java.lang.ProcessImpl.forkAndExec(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 19 common frames omitted
Exception in thread "AWT-EventQueue-0" java.lang.NumberFormatException: For input string: "IOException error
Cannot run program "IOException errorCannot run program "which": error=2, No such file or directory": error=2, No such file or directory"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(Unknown Source)
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(Unknown Source)
	at java.base/java.lang.Float.parseFloat(Unknown Source)
	at org.hvdw.jexiftoolgui.mainScreen.setProgramScreenTexts(mainScreen.java:3415)
	at org.hvdw.jexiftoolgui.mainScreen.<init>(mainScreen.java:3543)
	at org.hvdw.jexiftoolgui.mainScreen.createAndShowGUI(mainScreen.java:3568)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by hvdwolf** [comment]
Hi,

I use the program "which" to check if exiftool is installed on your Linux system.
"which" is part of your standard Linux installation as it is also used by Linux itself. There is nothing to install. It should simply be there.

Can you try in a terminal to simply execute the command `which` or `which exiftool`?

**Comment by sam302** [comment]
Hello thanks for the quick reply.

I did execute `which exiftool` and I got `/usr/bin/exiftool`

I added the above line to the prefs.xml file and saved it.  When I ran the appimage again I got the splashscreen again and then nothing.  I ran the image again and got the same popup.  Now when I look in that directory there is a new xml file called IncorrectFormatPrefs.xml.  I am sure I did something incorrectly when I edited the file.  I apologize I admittedly don't know anything about java.  Thanks for your help.

**Comment by hvdwolf** [comment]
Please try this [1.7.0-1](https://mega.nz/file/Vc8XjaDK#qrdnwic7NfC2CjRWXMs3i-0V63RmcRKk3FW2lm72pl8)

To try this: Please **first** remove the prefs.xml from your `/home/<username>/.java/.userPrefs/org/hvdw/jexiftoolgui` folder, so jExiftoolGUI will start completely fresh. Of course you can make a backup, but the folder needs to be empty or simply remove the `org/hvdw/jexiftoolgui` part completely.
Then start this new appimage and see if it works correctly now.

**Comment by sam302** [comment]
Works perfectly thank you.

**Comment by hvdwolf** [comment]
Thanks for the speedy response.
Will be in the next (bugfix) release. Hopefully this weekend.

**Comment by hvdwolf** [comment]
released in 1.7.1
